
const actions = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGIN_FATAL_ERROR: 'LOGIN_FATAL_ERROR',
    
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',

    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',
    REGISTER_FATAL_ERROR: 'REGISTER_FATAL_ERROR',

    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    UPDATE_ERROR: 'UPDATE_ERROR',
    UPDATE_FATAL_ERROR: 'UPDATE_FATAL_ERROR',

    UPDATE_EMAIL_SUCCESS: 'UPDATE_EMAIL_SUCCESS',
    UPDATE_EMAIL_ERROR: 'UPDATE_EMAIL_ERROR',
    UPDATE_EMAIL_FATAL_ERROR: 'UPDATE_EMAIL_FATAL_ERROR',

    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_ERROR: 'UPDATE_PASSWORD_ERROR',
    UPDATE_PASSWORD_FATAL_ERROR: 'UPDATE_PASSWORD_FATAL_ERROR',

    // customer //
    FETCH_CUSTOMERS: 'FETCH_CUSTOMERS',
    FETCH_CUSTOMERS_ERROR: 'FETCH_CUSTOMERS_ERROR',
    NEW_CUSTOMER: 'NEW_CUSTOMER',
    
}

export default actions

